apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: biasharaiq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage-pvc
  namespace: biasharaiq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
